defaults:
  - _self_

files:
  dataset_dir: './data/'
  models_dir: './models/'
  model_filename: 'model.pt'

params:
  seed: 42
  epoch_num: 1
  batch_size: 128
  lr: 0.001

mlflow_params:
  logging: true
  run_name: 'fashion'
  experiment: 'Fashion MNIST'

can_use_cuda: false
