name: pre-commit

on:
  pull_request:
  push:
    branches:
     - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: [ "3.10" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Set up the pre-commit cache
        uses: pre-commit/action@v3.0.0
